### PR TITLE
Impl `serde::{Deserialize, Serialize}` for `StrInner`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Review by vorner — CHANGES_REQUESTED** [review]
Hello

This seems like a good idea to have. But there's a bit of nitpicking:
* It's not 100% clear if it serializes that as a string or as an array of bytes. I think it _should_ be the former, but can we confirm by having an explicit test, maybe by storing to JSON and then loading it back?
* I have some preferences for style which this doesn't adhere to. I know I haven't written there anyway, but can I ask for:
  - Not nesting use statements, but having them as separate lines, that is `use serde::de::{..};` on one and `use serde::{Deserialize, Serialize}`
  - If a submodule becomes a directory, I prefer not to have both `string.rs` and `string/*` side by side. Can you use the (probably older) way of renaming `string.rs` to `string/mod.rs`? Or, preferably, have the new impls inside the `src/string.rs`, only annotated by the `#[cfg(..)]` directives (easier to find which impls exist)?

Thank you :-)

**Comment by NobodyXu** [comment]
> It's not 100% clear if it serializes that as a string or as an array of bytes. I think it should be the former, but can we confirm by having an explicit test, maybe by storing to JSON and then loading it back?

```rust
        let s = Deref::deref(self);
        s.serialize(serializer)
```

`s` there is `&str`, I can add an explicit annotation to it.

**Comment by NobodyXu** [comment]
@vorner I've fixed the serialization code and the style issue.

**Comment by vorner** [comment]
Thanks for the changes.

It's clearer it's string now, but I'd still like to have a round-trip test. I can add it if you prefer that.

Should I release the other thing or should I wait for this one first?

**Comment by NobodyXu** [comment]
> Should I release the other thing or should I wait for this one first?

I'm not in rush

**Comment by NobodyXu** [comment]
> It's clearer it's string now, but I'd still like to have a round-trip test. I can add it if you prefer that.

I will add unit tests using [`serde_test`](https://crates.io/crates/serde_test)

**Comment by NobodyXu** [comment]
@vorner I've added basic unit tests for `Str` and `StrMut`.

**Comment by vorner** [comment]
Thanks. I'm going to release it now.

**Pull request merged**
