### PR TITLE
Impl new fn `string::from_static`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by vorner** [comment]
Hello.

Looking at it, it seems this method is a good idea. But let me ask for two minor changes:

* This seems like it should have been a single commit, not 3 with intermediate somewhat-incomplete states. Can you squash it together to nicer history?
* `Bytes::from_static` is a `const` fn. I think it would make sense to make this new one const too.

**Comment by NobodyXu** [comment]
> This seems like it should have been a single commit, not 3 with intermediate somewhat-incomplete states. Can you squash it together to nicer history?

Sure

> Bytes::from_static is a const fn. I think it would make sense to make this new one const too.

Thanks for pointing that out!

**Comment by NobodyXu** [comment]
> Bytes::from_static is a const fn. I think it would make sense to make this new one const too.

Turns out that in order to do this, we also need to mark `StrInner::from_inner_unchecked` as const, which is fine because it doesn't perform anything.

**Comment by NobodyXu** [comment]
@vorner I've squashed all these commits into one.

**Comment by vorner** [comment]
Thank you :-)

**Pull request merged**
